"""Third commit

Revision ID: 5fc9173a4088
Revises: de9e12edbc8b
Create Date: 2021-05-26 20:02:36.390851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc9173a4088'
down_revision = 'de9e12edbc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'teacher_review',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('rating', 'company_review',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_unique_constraint(None, 'rating', ['work_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='unique')
    op.alter_column('rating', 'company_review',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('rating', 'teacher_review',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
