"""Initial migration.

Revision ID: c90f0f85f32a
Revises: 
Create Date: 2021-05-26 02:49:18.312416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90f0f85f32a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'password')
    op.create_unique_constraint('unique_project', 'project', ['title', 'company_id'])
    op.drop_column('student', 'password')
    op.drop_column('teacher', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_constraint('unique_project', 'project', type_='unique')
    op.add_column('company', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
