"""Second commit

Revision ID: de9e12edbc8b
Revises: c90f0f85f32a
Create Date: 2021-05-26 12:54:32.784280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9e12edbc8b'
down_revision = 'c90f0f85f32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'work', ['projects_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work', type_='unique')
    # ### end Alembic commands ###
